-- MySQL Script generated by MySQL Workbench
-- 03/25/19 13:25:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema glossary-tester
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `wordlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordlist` (
  `wordlistid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATE NOT NULL,
  `data` TEXT(65535) NOT NULL,
  PRIMARY KEY (`wordlistid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
